### ISSUE TITLE
redmine:4.0.3-passenger broken?

### ISSUE THREAD

**Issue by maximkrusina** [docker-library/redmine#160]
Hi, after upgrading from 4.0.2 to 4.0.3 (via redmine:4.0-passenger tag) our redmine instances broke. I'm total Ruby lama, but found this in log:

You can stop Phusion Passenger Standalone by pressing Ctrl-C.,
Problems? Check https://www.phusionpassenger.com/library/admin/standalone/troubleshooting/,
===============================================================================,
[ N 2019-04-04 17:34:49.4314 42/Tf age/Cor/SecurityUpdateChecker.h:519 ]: Security update check: no update found (next check in 24 hours),
App 83 output: W, [2019-04-04T17:34:52.452809 #83]  WARN -- : Creating scope :system. Overwriting existing method Enumeration.system.,
App 83 output: W, [2019-04-04T17:34:53.505299 #83]  WARN -- : Creating scope :sorted. Overwriting existing method Group.sorted.,
App 83 output: W, [2019-04-04T17:34:53.519129 #83]  WARN -- : Creating scope :sorted. Overwriting existing method User.sorted.,
App 83 output: W, [2019-04-04T17:34:53.722368 #83]  WARN -- : Creating scope :visible. Overwriting existing method AgileQuery.visible.,
App 83 output: Error: The application encountered the following error: undefined local variable or method `acts_as_colored' for Project (call 'Project.connection' to establish a connection):Class,
App 83 output: Did you mean?  acts_as_tree (NameError),
App 83 output:     /usr/local/bundle/gems/activerecord-5.2.2.1/lib/active_record/dynamic_matchers.rb:22:in `method_missing',
App 83 output:     /usr/src/redmine/plugins/redmine_agile/lib/redmine_agile/patches/project_patch.rb:27:in `block in included',
App 83 output:     /usr/src/redmine/plugins/redmine_agile/lib/redmine_agile/patches/project_patch.rb:25:in `class_eval',
App 83 output:     /usr/src/redmine/plugins/redmine_agile/lib/redmine_agile/patches/project_patch.rb:25:in `included',
App 83 output:     /usr/src/redmine/plugins/redmine_agile/lib/redmine_agile/patches/project_patch.rb:38:in `include',
App 83 output:     /usr/src/redmine/plugins/redmine_agile/lib/redmine_agile/patches/project_patch.rb:38:in `<top (required)>',
App 83 output:     /usr/local/bundle/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:291:in `require',

PS: I tried to uninstall plugins one by one and recretaing Redmine instance but it didnt helped. It seems that there is some connection to Upgrade to Rails 5.2.2.1 where something was removed, don't remeber what :) some hook or so.

**Comment by maximkrusina** [comment]
PS: going back from **redmine:4.0-passenger** to **redmine:4.0.2-passenger** helped

**Comment by maximkrusina** [comment]
This is the error I got: The application encountered the following error: undefined method `before_filter'

Some clue: https://github.com/piotrmurach/loaf/issues/9

**Comment by wglambert** [comment]
Looks like a rails error with some deprecations in the version your using

https://guides.rubyonrails.org/5_0_release_notes.html#action-pack-deprecations
>Deprecated all *_filter callbacks in favor of *_action callbacks.

Odd that you don't encounter errors with 5.2.2, but do with the bump to 5.2.2.1

I'd try asking over at the [redmine forums](https://www.redmine.org/projects/redmine/boards) for help with rails version upgrades

**Comment by e2-online** [comment]
Workaround: set environment variable `PASSENGER_DISABLE_SECURITY_UPDATE_CHECK=true`
Source: https://www.phusionpassenger.com/library/config/standalone/reference/#--disable-security-update-check-disable_security_update_check

**Comment by maximkrusina** [comment]
Maybe it will be a good idea to add an note to docker readme, to warn all users, ok?

**Comment by tianon** [comment]
The backtrace in the OP pretty clearly is an issue happening in the `redmine_agile` plugin -- I'd suggest reaching out to the maintainer of that to see if they have any idea why their plugin isn't working on the latest Redmine release.

**Comment by maximkrusina** [comment]
> The backtrace in the OP pretty clearly is an issue happening in the `redmine_agile` plugin -- I'd suggest reaching out to the maintainer of that to see if they have any idea why their plugin isn't working on the latest Redmine release.

Sure, but it seems that it's not caused by a bug in plugin, but there is rather some deprecation of some Rails hooks (ssry, I'm not RoR developer). I tried to disable all plugins one-by-one, and the problems still popped oout for each plugin.

**Comment by goodnewz** [comment]
Looks like plugin devs have been informed: https://www.redmineup.com/projects/qa/questions/216-agile-plugin-not-working ..see response two.

**Comment by yosifkit** [comment]
> it is a known one and our developers are already working on the fix.
>
> \- https://www.redmineup.com/projects/qa/questions/216-agile-plugin-not-working

Given that this is a bug in the plugin and not in the image I will close.
